services:

  postgres:
    image: postgres:15
    container_name: airflow_postgres

    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow-init:
    image: apache/airflow:2.10.5
    user: "0:0"
    
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./data:/opt/airflow/data
      - ./plugins:/opt/airflow/plugins

    depends_on:
      - postgres

    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW_CONN_POSTGRES_DESTINO: "postgresql://coder-ra-c6:Riwi2026**@15.204.173.204:6432/postgres"

      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow

    command: >
      bash -c "
      airflow db migrate &&
      airflow users create
      --username admin
      --firstname Camilo
      --lastname Guengue
      --role Admin
      --email admin@admin.com
      --password admin
      "

  airflow-webserver:
    image: apache/airflow:2.10.5
    user: "0:0"

    container_name: airflow_webserver

    depends_on:
      - postgres

    restart: always

    ports:
      - "8080:8080"

    environment:

      AIRFLOW__CORE__EXECUTOR: LocalExecutor

      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow

    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./data:/opt/airflow/data

    command: webserver

  airflow-scheduler:
    image: apache/airflow:2.10.5
    user: "0:0"
    container_name: airflow_scheduler

    depends_on:
      - postgres

    restart: always

    environment:

      AIRFLOW__CORE__EXECUTOR: LocalExecutor

      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow

    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./data:/opt/airflow/data

    command: scheduler

volumes:
  postgres_data: